### ISSUE TITLE
"Files" raw content is dumped into release body.

### ISSUE THREAD

**Issue by BlakeDarrow** [irongut/EditRelease#141]
## Bug Report

When using the "files" argument, whenever this action is run, the actual contents of the file are the new release body message.

### Workflow File
```yaml
- name: Add recipes to existing release
   uses: irongut/EditRelease@v1.2.0
   with:
     token: ${{ secrets.PAT }}
     id: 104329126
     files: "Recipes-${{ steps.set_file_name.outputs.file_name }}.zip"
```

### Actions Log
```
Repository: BlakeDarrow/DarrowRecipes, Release Id: 104329[12](https://github.com/BlakeDarrow/DarrowRecipes/actions/runs/5085637940/jobs/9139294221#step:9:13)6
Release Found - Id: 104329126, Tag: Recipes, Author: BlakeDarrow.
Release Updated - Id: 104329126, Tag: Recipes, Author: BlakeDarrow.
```

### Expected Behavior
I would assume the "files" would append a new file to the release, not dump the raw contents into the message body.

### Additional Context
I have tried using all the arguments that you provide to see if it was some unexpected behavior because I don't have a "body" arguments provided, but no dice.

edit: spacing
