### ISSUE TITLE
Implement StepSecurity Secure Workflows (policy)

### ISSUE THREAD

**Issue by irongut** [irongut/EditRelease#22]
## Feature Request

Implement [StepSecurity Secure Workflows](https://github.com/step-security/secure-workflows) Harden Runner recommendations.

### Expected Behaviour

Workflows will be updated following the recommendations.

### Additional Context

Actions not currently in the StepSecurity token permission database:
- samspills/assign-pr-to-author

### Linked To
#21 Implement StepSecurity Secure Workflows (audit)

**Comment by irongut** [comment]
## Assign to Project 

Step | Domain
---- | ------
Assign Issues + PRs (srggrs/assign-one-project-github-action) | api.github.com:443

```yml
- name: Harden Runner
  uses: step-security/harden-runner@74b568e8591fbb3115c70f3436a0c6b0909a8504
  with:
    egress-policy: block
    allowed-endpoints: >
      api.github.com:443
```

## Auto PR

Step | Domain
---- | ------
Assign PR (samspills/assign-pr-to-author) | api.github.com:443

```yml
- name: Harden Runner
  uses: step-security/harden-runner@74b568e8591fbb3115c70f3436a0c6b0909a8504
  with:
    egress-policy: block
    allowed-endpoints: >
      api.github.com:443
```

## Mark Stale

Step | Domain
---- | ------
Stale(actions/stale) | api.github.com:443

```yml
- name: Harden Runner
  uses: step-security/harden-runner@74b568e8591fbb3115c70f3436a0c6b0909a8504
  with:
    egress-policy: block
    allowed-endpoints: >
      api.github.com:443
```

## PR Labeller

Step | Domain
---- | ------
Stale(actions/labeler) | api.github.com:443
Post Complete (Runner.Worker) | pipelines.actions.githubusercontent.com:443

```yml
- name: Harden Runner
  uses: step-security/harden-runner@74b568e8591fbb3115c70f3436a0c6b0909a8504
  with:
    egress-policy: block
    allowed-endpoints: >
      api.github.com:443
```
