### ISSUE TITLE
`Error: Octokit.ApiValidationException - Validation Failed` with files

### ISSUE THREAD

**Issue by Ulthran** [irongut/EditRelease#243]
## Bug Report

Trying to add a file to a release and getting `Error: Octokit.ApiValidationException - Validation Failed`. The same workflow succeeds without including the file.

### Workflow File
```yaml
generate-tarball:
        name: Generate Tarball and Add to Release
        runs-on: ubuntu-latest
        needs:
          - run-tests
          - check-version
    
        steps:
          - name: Checkout Code
            uses: actions/checkout@v4

          - name: Generate Tarball
            run: bash dev_scripts/generate_archive.sh

          - name: Upload Tarball
            uses: actions/upload-artifact@v2
            with:
              name: sunbeam.tar.gz
              path: sunbeam.tar.gz

          - name: Add Tarball to Release
            uses: irongut/EditRelease@v1.2.0
            with:
              token: ${{ secrets.GITHUB_TOKEN }}
              id: ${{ github.event.release.id }}
              body: "### Sunbeam Tarball\nDownload the Sunbeam tarball from the release page to install Sunbeam locally.\n[Download Sunbeam Tarball](https://github.com/sunbeam-labs/sunbeam/releases/${{ needs.check-version.outputs.version-without-v }}/download/sunbeam.tar.gz"
              replacebody: false
              files: "sunbeam.tar.gz"
```

### Actions Log
```
Run irongut/EditRelease@v1.2.0
  with:
    token: ***
    id: 149431886
    body: ### Sunbeam Tarball
  Download the Sunbeam tarball from the release page to install Sunbeam locally.
  [Download Sunbeam Tarball](https://github.com/sunbeam-labs/sunbeam/releases/4.5.[2](https://github.com/sunbeam-labs/sunbeam/actions/runs/8526153389/job/23354919734#step:6:2).dev3/download/sunbeam.tar.gz
    replacebody: false
    files: sunbeam.tar.gz
    replacename: false
    spacing: 1
/usr/bin/docker run --name ghcrioironguteditreleasev120_2f0244 --label 0a6120 --workdir /github/workspace --rm -e "INPUT_TOKEN" -e "INPUT_ID" -e "INPUT_BODY" -e "INPUT_REPLACEBODY" -e "INPUT_FILES" -e "INPUT_NAME" -e "INPUT_REPLACENAME" -e "INPUT_DRAFT" -e "INPUT_PRERELEASE" -e "INPUT_SPACING" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_ENVIRONMENT" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e "ACTIONS_RESULTS_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/sunbeam/sunbeam":"/github/workspace" ghcr.io/irongut/editrelease:v1.2.0  "--token" "***" "--id" "1494[3](https://github.com/sunbeam-labs/sunbeam/actions/runs/8526153389/job/23354919734#step:6:3)1886" "--name" "" "--replacename" "false" "--draft" "" "--prerelease" "" "--body" "### Sunbeam Tarball
Download the Sunbeam tarball from the release page to install Sunbeam locally.
[Download Sunbeam Tarball](https://github.com/sunbeam-labs/sunbeam/releases/[4](https://github.com/sunbeam-labs/sunbeam/actions/runs/8526153389/job/23354919734#step:6:4).5.2.dev3/download/sunbeam.tar.gz" "--replacebody" "false" "--files" "sunbeam.tar.gz" "--spacing" "1"
EditRelease v1.2.0.0 started...
Repository: sunbeam-labs/sunbeam, Release Id: 149431886
Release Found - Id: 149431886, Tag: v4.[5](https://github.com/sunbeam-labs/sunbeam/actions/runs/8526153389/job/23354919734#step:6:5).2.dev3, Author: Ulthran.
Error: Octokit.ApiValidationException - Validation Failed
```

### Expected Behavior
It should add the file to the release.

### Additional Context
Wasn't sure if the action looks for the file locally or as an artifact so added the step to upload it as an artifact. Fails with and without.
